channels:
  - conda-forge
  - defaults
dependencies:
  - streamlit=1.10.0
  - streamlit-folium
  - pandas=1.4.2
  - geopandas=0.10.2
  - pyproj=3.3.1
  - folium=0.12.1.post1
  - pillow=9.0.1
