name: python-gis
channels:
  - conda-forge
  - defaults
dependencies:
  - streamlit=1.10.0=pyhd8ed1ab_1
  - streamlit-folium=0.6.12=pyhd8ed1ab_0
  - pandas
  - geopandas=0.10.2=pyhd8ed1ab_1
  - pyproj
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - pillow

